### ISSUE TITLE
Stalls on "processing results"

### ISSUE THREAD

**Issue by Masonavic** [hoosierEE/ChromeDuino#1]
I'm trying to upload a sketch to the Arduino Uno, and it stalls on "Processing results." The program sees & connects to the USB device, it just won't run a sketch. Chrome OS version 54.0.2840.101.

**Comment by hoosierEE** [comment]
Hi, uploading was never a feature of this project, sorry if that wasn't clear.

Looks like codebender.cc is shutting down, but you might check out https://github.com/jacobrosenthal/browserdude as a potential alternative for what you want to do.
